version: 2
updates:
  - package-ecosystem: "npm" # Replace with the appropriate package ecosystem (e.g., "npm", "docker", "composer", etc.)
    directory: "/" # Update with the path to the directory containing your package manifests
    schedule:
      interval: "weekly"

